apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: home-lab-eks
  region: ap-south-1
  version: "1.33"

vpc:
  id: "vpc-0b9b782aa111c0bde"
  subnets:
    public:
      ap-south-1a:
        id: "subnet-04027f0848e3d6ddc"
      ap-south-1b:
        id: "subnet-054ec56f89ed69000"
    private:
      ap-south-1a:
        id: "subnet-0aebdc9e65178d534"
      ap-south-1b:
        id: "subnet-080ce0a4f33fbcc99"

iam:
  withOIDC: true

managedNodeGroups:
- name: spot-nodes
  instanceTypes: [ "t3.small", "t3a.small", "t2.small" ] # Diversity for better spot availability
  minSize: 1
  maxSize: 3
  desiredCapacity: 1
  spot: true
  privateNetworking: true # Nodes in private subnets with NAT for outbound access
