apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: home-lab-eks
  region: ap-south-1
  version: "1.33"

vpc:
  id: "vpc-0b9b782aa111c0bde"
  subnets:
    public:
      ap-south-1a:
        id: "subnet-04027f0848e3d6ddc"
      ap-south-1b:
        id: "subnet-054ec56f89ed69000"
    private:
      ap-south-1a:
        id: "subnet-0aebdc9e65178d534"
      ap-south-1b:
        id: "subnet-080ce0a4f33fbcc99"

managedNodeGroups:
- name: spot-nodes
  instanceTypes: [ "t3.small", "t3a.small", "t2.small" ] # Diversity for better spot availability
  minSize: 1
  maxSize: 3
  desiredCapacity: 1
  spot: true
  privateNetworking: true # Nodes in private subnets with NAT for outbound access
  ssh:
    allow: true
    publicKeyName: ASWATH-ADMIN
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoScaler: true
      externalDNS: true
      certManager: true
      appMesh: true
      appMeshPreview: true
      ebs: true
      fsx: true
      efs: true
      awsLoadBalancerController: true
      xRay: true
      cloudWatch: true
      albIngress: true
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: s3-dynamodb-full-access
      labels: { aws-usage: "application" }
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
    - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
