# Loki Configuration for EKS with S3 Storage - Based on Official Documentation
loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
    - from: "2024-04-01"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
  storage_config:
    aws:
      region: ap-south-1
      bucketnames: home-lab-eks-loki
      s3forcepathstyle: false
  pattern_ingester:
    enabled: false
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention
  storage:
    type: s3
    bucketNames:
      chunks: home-lab-eks-loki
      ruler: home-lab-eks-loki
      admin: home-lab-eks-loki
    s3:
      region: ap-south-1
      s3ForcePathStyle: false
      insecure: false
  ruler:
    enable_api: true

# Disable minio storage for production S3 usage
minio:
  enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    storageClass: gp3
    accessModes:
    - ReadWriteOnce
    size: 30Gi
  # Disable anti-affinity for single node cluster
  affinity: {}
  # Ensure no pod disruption budget conflicts
  podDisruptionBudget:
    enabled: false
  resources:
  requests:
    cpu: 50m
    memory: 192Mi
  limits:
    cpu: 300m
    memory: 384Mi

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

# Service account with IRSA annotations - script will update the role ARN
serviceAccount:
  create: true
  name: loki-sa
  annotations:
    eks.amazonaws.com/role-arn: ""
  automountServiceAccountToken: true

# Gateway configuration - single replica for single node
gateway:
  enabled: false

# Disable anti-affinity globally for single node deployment  
global:
  dnsService: "kube-dns"
