deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 10Gi
simpleScalable:
  replicas: 0
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: s3
    bucketNames:
      chunks: home-lab-eks-loki
      index: home-lab-eks-loki
      ruler: home-lab-eks-loki
    s3:
      endpoint: s3.ap-south-1.amazonaws.com
      region: ap-south-1
  storage_config:
    s3:
      endpoint: s3.ap-south-1.amazonaws.com
      bucket_name: home-lab-eks-loki
      region: ap-south-1
      s3forcepathstyle: false
  schema_config:
    configs:
    - from: "2020-10-01"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: lokiindex
        period: 24h
  limits_config:
    retention_period: 30d
  memberlistConfig: {}
  resultsCache:
    enabled: false
serviceAccount:
  create: false
  name: loki-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::058264195463:role/home-lab-eks-loki-s3-role
