apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-pvc
  namespace: uptime
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
