apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-deployment
  namespace: vaultwarden
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 3012
          name: websocket
        env:
        - name: DOMAIN
          value: "https://password.init0xff.com"
        - name: SIGNUPS_ALLOWED
          value: "true"
        - name: INVITATIONS_ALLOWED
          value: "true"
        - name: WEBSOCKET_ENABLED
          value: "true"
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vaultwarden-secrets
              key: ADMIN_TOKEN
        - name: ROCKET_PORT
          value: "8080"
        - name: ROCKET_WORKERS
          value: "10"
        - name: SHOW_PASSWORD_HINT
          value: "false"
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /alive
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /alive
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vaultwarden-data
