# observability/grafana/values.yaml
persistence:
  enabled: true
  type: pvc
  storageClassName: gp3
  size: 2Gi

adminPassword: your-grafana-password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Mimir
      type: prometheus
      access: proxy
      # If using the mimir-distributed chart (recommended): use the nginx service
      url: http://mimir-nginx.observability.svc.cluster.local/prometheus
      isDefault: true
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.observability.svc.cluster.local

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
  - grafana.init0xff.com
  path: /
  pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
