persistence:
  enabled: true
  type: pvc
  storageClassName: gp3
  size: 2Gi

adminPassword: your-grafana-password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.lens-metrics.svc.cluster.local:80
      isDefault: true
      basicAuth: false
      editable: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.lens-metrics.svc.cluster.local:3100
      basicAuth: false
      editable: true
      jsonData:
        maxLines: 1000

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
  - grafana.init0xff.com
  path: /
  pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Enhanced Grafana configuration
grafana.ini:
  analytics:
    check_for_updates: false
  log:
    mode: console
    level: info
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  server:
    domain: grafana.init0xff.com
    root_url: http://grafana.init0xff.com
  users:
    allow_sign_up: false
    auto_assign_org: true
    auto_assign_org_role: Viewer
  auth.anonymous:
    enabled: false
